### ISSUE TITLE
URL detection breaks some Apache Camel thread dumps

### ISSUE THREAD

**Issue by maisi** [jstack-review/jstack-review#10]
Hello, 

while using your tool I've encountered an issue that some Apache Camel thread dumps won’t be analyzed because they include an URL in their name.

Example: 
```
"Camel (camel) thread #2 - eft://http://saas-eft:8008/bshatlas" #95 daemon prio=5 os_prio=0 tid=0x00007fef7fb60800 nid=0x41ba runnable [0x00007fef310e9000]
   java.lang.Thread.State: RUNNABLE
	at sun.nio.ch.FileDispatcherImpl.read0(Native Method)
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39)
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
	at sun.nio.ch.IOUtil.read(IOUtil.java:197)
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:377)
	- locked <0x00000000851def98> (a java.lang.Object)
	at oracle.net.nt.TimeoutSocketChannel.read(TimeoutSocketChannel.java:178)
	at oracle.net.ns.NSProtocolNIO.doSocketRead(NSProtocolNIO.java:544)
	at oracle.net.ns.NIOPacket.readHeader(NIOPacket.java:234)
	at oracle.net.ns.NIOPacket.readPacketFromSocketChannel(NIOPacket.java:174)
	at oracle.net.ns.NIOPacket.readFromSocketChannel(NIOPacket.java:122)
	at oracle.net.ns.NIOPacket.readFromSocketChannel(NIOPacket.java:100)
[...]
```

I've created a fork and commented out the lines responsible for URL detection, after which the thread dumps will be analyzed as expected. (https://github.com/maisi/jstack-review/commit/a9f99fa8e8e366299b54203e3550ac446feff004) 
However this essentially breaks the import-from-URL feature, which is why I haven't submitted a pull request. 

Thanks for your tool, really helps with my daily work :) 

BR
Martin

**Comment by elmuerte** [comment]
Should be fixed now. I made the URL checking on the input more strict.
