### ISSUE TITLE
Thread state "WAITING (parking)" from OpenJDK 11 not recognized well

### ISSUE THREAD

**Issue by twhitmorenz** [jstack-review/jstack-review#17]
Stack dumps taken using JStack tool from OpenJDK 11 use a "WAITING (parking)" value in the Thread State line which JStack Review doesn't appear to recognize in the ThreadStatus.determineStatus() function.

Examining the Hotspot C++ source code it seems there are a couple of states possibly not recognized:
-  "WAITING (parking)"
- "TIMED_WAITING (parking)"
- "BLOCKED (on object monitor)"

The below C++ code seems to be the source of the Thread Statuses that are rendered. See:
- https://github.com/openjdk/jdk11u/blob/master/src/hotspot/share/classfile/javaClasses.cpp#L1769
- (called from https://github.com/openjdk/jdk11u/blob/master/src/hotspot/share/runtime/thread.cpp#L3012, https://github.com/openjdk/jdk11u/blob/master/src/hotspot/share/runtime/thread.cpp#L4686, https://github.com/openjdk/jdk11u/blob/a046767fe01a2d02ec81dcba2bd0a43e435dc709/src/hotspot/share/runtime/vmOperations.cpp#L214, https://github.com/openjdk/jdk11u/blob/master/src/hotspot/share/services/diagnosticCommand.cpp#L641)

Other parts of synchronizer recognition logic (eg the `this.thread.wantNotificationOn !== null` condition) compensate for this analysis in some cases, but it would seem desirable to recognize the Thread State correctly.

Example below ----

"second thread" #15 prio=5 os_prio=0 cpu=0.00ms elapsed=21.96s tid=0x000001d9f6cd7800 nid=0x2604 waiting on condition  [0x000000569beff000]
   java.lang.Thread.State: WAITING (parking)
	at jdk.internal.misc.Unsafe.park(java.base@11.0.21/Native Method)
	- parking to wait for  <0x0000000622759690> (a java.util.concurrent.locks.ReentrantLock$NonfairSync)
	at java.util.concurrent.locks.LockSupport.park(java.base@11.0.21/LockSupport.java:194)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.parkAndCheckInterrupt(java.base@11.0.21/AbstractQueuedSynchronizer.java:885)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireQueued(java.base@11.0.21/AbstractQueuedSynchronizer.java:917)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquire(java.base@11.0.21/AbstractQueuedSynchronizer.java:1240)
	at java.util.concurrent.locks.ReentrantLock.lock(java.base@11.0.21/ReentrantLock.java:267)
	at com.orchestral.rhapsody.util.thread.ThreadDumpFormatterTest.lambda$0(ThreadDumpFormatterTest.java:67)
	- locked <0x0000000622759640> (a java.lang.Object)
	at com.orchestral.rhapsody.util.thread.ThreadDumpFormatterTest$$Lambda$307/0x00000008001a4840.run(Unknown Source)
	at java.lang.Thread.run(java.base@11.0.21/Thread.java:829)

[jstack waiting parking.txt](https://github.com/jstack-review/jstack-review/files/13048615/jstack.waiting.parking.txt)

**Comment by elmuerte** [comment]
Thanks. I've added the missing thread states.
